version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    environment:
      - DATADOG_AGENT=datadog # used to initialize the Datadog library
    container_name: app

  # Run datadog agent in a container.
  datadog:
    container_name: datadog
    image: datadog/agent:latest
    environment:
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_SITE=datadoghq.eu # required if datadog site is https://app.datadoghq.eu/
      - DD_API_KEY=<API KEY HERE>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    links:
      - app